############################################################
#  	Глобальные параметры
############################################################

# "handlers" задаёт список классов-обработчиков логов через запятую.
# Эти обработчики устанавливаются при запуске виртуальной машины. Учтите, что данные классы должны быть в системном classpath.
# По умолчанию мы настраиваем только ConsoleHandler, который показывает сообщения уровня INFO и выше.
#handlers= java.util.logging.ConsoleHandler

# Чтобы добавить ещё и FileHandler, используйте вместо неё строку ниже.
handlers = java.util.logging.FileHandler,\
		java.util.logging.ConsoleHandler,\
		net.sf.l2j.commons.logging.handler.ErrorLogHandler

chat.handlers = net.sf.l2j.commons.logging.handler.ChatLogHandler
chat.useParentHandlers = false

gmaudit.handlers = net.sf.l2j.commons.logging.handler.GMAuditLogHandler
gmaudit.useParentHandlers = false

item.handlers = net.sf.l2j.commons.logging.handler.ItemLogHandler
item.useParentHandlers = false


# Глобальный уровень логирования по умолчанию.
# Определяет, какие события записываются во всех логгерах.
# Для каждой конкретной подсистемы этот глобальный уровень может быть переопределён собственным уровнем.
# Учтите, что у ConsoleHandler есть отдельная настройка уровня, ограничивающая вывод сообщений в консоль.
.level= CONFIG

############################################################
# Параметры конкретных обработчиков.
# Описывают настройки, специфичные для каждого обработчика.
############################################################

# консоль
java.util.logging.ConsoleHandler.formatter = net.sf.l2j.commons.logging.formatter.ConsoleLogFormatter
java.util.logging.ConsoleHandler.level = FINER

# по умолчанию вывод в файл выполняется в домашний каталог пользователя.
java.util.logging.FileHandler.pattern = log/console/console_%g.txt
java.util.logging.FileHandler.limit = 1000000
java.util.logging.FileHandler.count = 5
java.util.logging.FileHandler.formatter = net.sf.l2j.commons.logging.formatter.FileLogFormatter
java.util.logging.FileHandler.level = CONFIG

# логирование ошибок (исключений)
net.sf.l2j.commons.logging.handler.ErrorLogHandler.pattern = log/error/error_%g.txt
net.sf.l2j.commons.logging.handler.ErrorLogHandler.limit = 1000000
net.sf.l2j.commons.logging.handler.ErrorLogHandler.count = 5
net.sf.l2j.commons.logging.handler.ErrorLogHandler.formatter = java.util.logging.SimpleFormatter
net.sf.l2j.commons.logging.handler.ErrorLogHandler.filter = net.sf.l2j.commons.logging.filter.ErrorFilter
net.sf.l2j.commons.logging.handler.ErrorLogHandler.level = CONFIG

# логирование чатов
net.sf.l2j.commons.logging.handler.ChatLogHandler.pattern = log/chat/chat_%g.txt
net.sf.l2j.commons.logging.handler.ChatLogHandler.limit = 1000000
net.sf.l2j.commons.logging.handler.ChatLogHandler.count = 5
net.sf.l2j.commons.logging.handler.ChatLogHandler.formatter = net.sf.l2j.commons.logging.formatter.ChatLogFormatter
net.sf.l2j.commons.logging.handler.ChatLogHandler.filter = net.sf.l2j.commons.logging.filter.ChatFilter
net.sf.l2j.commons.logging.handler.ChatLogHandler.append = true
net.sf.l2j.commons.logging.handler.ChatLogHandler.level = INFO

# логирование действий ГМов (GM Audit)
net.sf.l2j.commons.logging.handler.GMAuditLogHandler.pattern = log/gmaudit/gmaudit_%g.txt
net.sf.l2j.commons.logging.handler.GMAuditLogHandler.limit = 1000000
net.sf.l2j.commons.logging.handler.GMAuditLogHandler.count = 5
net.sf.l2j.commons.logging.handler.GMAuditLogHandler.formatter = net.sf.l2j.commons.logging.formatter.GMAuditFormatter
net.sf.l2j.commons.logging.handler.GMAuditLogHandler.filter = net.sf.l2j.commons.logging.filter.GMAuditFilter
net.sf.l2j.commons.logging.handler.GMAuditLogHandler.append = true
net.sf.l2j.commons.logging.handler.GMAuditLogHandler.level = INFO

# логирование предметов
net.sf.l2j.commons.logging.handler.ItemLogHandler.pattern = log/item/item_%g.txt
net.sf.l2j.commons.logging.handler.ItemLogHandler.limit = 1000000
net.sf.l2j.commons.logging.handler.ItemLogHandler.count = 5
net.sf.l2j.commons.logging.handler.ItemLogHandler.formatter = net.sf.l2j.commons.logging.formatter.ItemLogFormatter
net.sf.l2j.commons.logging.handler.ItemLogHandler.filter = net.sf.l2j.commons.logging.filter.ItemFilter
net.sf.l2j.commons.logging.handler.ItemLogHandler.append = true
net.sf.l2j.commons.logging.handler.ItemLogHandler.level = INFO


############################################################
# Параметры конкретных подсистем.
# Дают дополнительный контроль над каждым логгером.
############################################################

# Например, чтобы логгер com.xyz.foo писал только сообщения уровня SEVERE:
net.sf.l2j.gameserver.level = CONFIG
net.sf.l2j.loginserver.level = CONFIG
