# ===========================================================================
# Защита
# ===========================================================================
# Защита от автоматизированных клиентов и флуда пакетами.


# ---------------------------------------------------------------------------
# Сторонние клиенты
# ---------------------------------------------------------------------------

# Базовая защита от L2Walker.
# По умолчанию: False
L2WalkerProtection = False


# ---------------------------------------------------------------------------
# Защита от флуда
# ---------------------------------------------------------------------------
# Минимальная задержка в мс между двумя выполнениями одного и того же
# действия. 0 отключает соответствующую защиту.

# По умолчанию: 4200
RollDiceTime = 4200

# По умолчанию: 10000
HeroVoiceTime = 10000

# По умолчанию: 2000
SubclassTime = 2000

# По умолчанию: 1000
DropItemTime = 1000

# По умолчанию: 100
ServerBypassTime = 100

# По умолчанию: 100
MultisellTime = 100

# По умолчанию: 300
ManufactureTime = 300

# По умолчанию: 3000
ManorTime = 3000

# По умолчанию: 10000
SendMailTime = 10000

# По умолчанию: 3000
CharacterSelectTime = 3000

# По умолчанию: 0
GlobalChatTime = 0

# По умолчанию: 0
TradeChatTime = 0

# По умолчанию: 2000
SocialTime = 2000
