# ===========================================================================
# Protection
# ===========================================================================
# Protections against automated clients and packet flooding.


# ---------------------------------------------------------------------------
# Third party clients
# ---------------------------------------------------------------------------

# Basic protection against L2Walker.
# Default: False
L2WalkerProtection = False


# ---------------------------------------------------------------------------
# Flood protectors
# ---------------------------------------------------------------------------
# Minimum delay, in ms, between two occurrences of the same action. 0 disables
# the related protector.

# Default: 4200
RollDiceTime = 4200

# Default: 10000
HeroVoiceTime = 10000

# Default: 2000
SubclassTime = 2000

# Default: 1000
DropItemTime = 1000

# Default: 100
ServerBypassTime = 100

# Default: 100
MultisellTime = 100

# Default: 300
ManufactureTime = 300

# Default: 3000
ManorTime = 3000

# Default: 10000
SendMailTime = 10000

# Default: 3000
CharacterSelectTime = 3000

# Default: 0
GlobalChatTime = 0

# Default: 0
TradeChatTime = 0

# Default: 2000
SocialTime = 2000
