# ===========================================================================
# Инстансы
# ===========================================================================
# Групповой контент, создаваемый отдельно для каждой группы: Four Sepulchers
# и Dimensional Rift.


# ---------------------------------------------------------------------------
# Four Sepulchers
# ---------------------------------------------------------------------------

# Количество членов группы, необходимое для входа. Ограничено рамками 2 - 9.
# По умолчанию: 4
NeededPartyMembers = 4


# ---------------------------------------------------------------------------
# Dimensional Rift
# ---------------------------------------------------------------------------

# Количество членов группы, необходимое для входа. На официальных серверах 2,
# и вся группа выбрасывается наружу, как только их становится меньше.
# По умолчанию: 2
RiftMinPartySize = 2

# Задержка в минутах между двумя автоматическими перемещениями, плюс
# случайное количество 30-секундных интервалов. На официальных серверах
# 8 минут плюс от 0 до 5 интервалов.
# По умолчанию: 8 / 5
AutoJumpsDelayMin = 8
AutoJumpsDelayRnd = 5

# Количество Dimensional Fragment, которое платит каждый член группы за вход,
# в зависимости от уровня рифта.
# По умолчанию: 21 / 24 / 27 / 30 / 33 / 36
RecruitCost = 21
SoldierCost = 24
OfficerCost = 27
CaptainCost = 30
CommanderCost = 33
HeroCost = 36

# Шанс в %, что при перемещении группу закинет к рейд-боссу Anakazel.
# По умолчанию: 15
AnakazelPortChance = 15
