package net.sf.l2j.gameserver.data.xml;

import java.nio.file.Path;

import net.sf.l2j.commons.data.xml.IXmlReader;

import net.sf.l2j.Config;
import net.sf.l2j.gameserver.enums.DropType;

import org.w3c.dom.Document;
import org.w3c.dom.NamedNodeMap;
import org.w3c.dom.Node;

/**
 * This class loads and stores the whole appearance of the drop list window, described by data/xml/droplist.xml.<br>
 * <br>
 * Everything the player sees is defined there : column widths and captions (&lt;layout&gt;), colors (&lt;colors&gt;) and labels (&lt;labels&gt;) - the tab of every {@link DropType} included. The
 * behavior is server side instead, on config/mods/droplist.properties : whether the window exists at all, which skill unlocks it, how many rows a page holds, whether the spoil tab is shown and
 * whether the rates are folded into the shown chances.<br>
 * <br>
 * The window itself is generated by {@link net.sf.l2j.gameserver.data.manager.DropListManager}.
 */
public class DropListData implements IXmlReader
{
	private int _width;
	private int _rowHeight;
	private int _headerHeight;
	private int _tabHeight;
	private int _iconSize;
	private int _maxPages;
	private int _pageHeight;
	private int _overhead;
	private int _nameChars;
	private String _ellipsis;

	private int _iconWidth;
	private int _nameWidth;
	private int _countWidth;
	private int _chanceWidth;

	private int _highChance;
	private int _mediumChance;

	private String _rowColor;
	private String _altRowColor;
	private String _headerColor;
	private String _headerTextColor;
	private String _titleColor;
	private String _tabBarColor;
	private String _tabColor;
	private String _activeTabColor;
	private String _nameColor;
	private String _countColor;
	private String _highChanceColor;
	private String _mediumChanceColor;
	private String _lowChanceColor;
	private String _disabledColor;
	private String _pageColor;
	private String _activePageColor;

	private String _itemHeader;
	private String _countHeader;
	private String _chanceHeader;
	private String _dropLabel;
	private String _currencyLabel;
	private String _spoilLabel;
	private String _herbLabel;
	private String _emptyLabel;
	private String _prevPageLabel;
	private String _nextPageLabel;

	protected DropListData()
	{
		load();
	}

	@Override
	public void load()
	{
		setDefaultLayout();
		setDefaultColors();
		setDefaultLabels();

		// IXmlReader only catches the parser exceptions ; without this, a single malformed attribute would abort the whole server startup.
		try
		{
			parseFile("./data/xml/droplist.xml");
		}
		catch (Exception e)
		{
			LOGGER.error("Couldn't fully read droplist.xml ; the drop list window runs on whatever has been read so far.", e);
		}
	}

	@Override
	public void parseDocument(Document doc, Path path)
	{
		forEach(doc, "list", listNode ->
		{
			forEach(listNode, "layout", layoutNode ->
			{
				final NamedNodeMap attrs = layoutNode.getAttributes();

				_width = Math.max(1, parseInt(attrs, "width", _width));
				_rowHeight = Math.max(1, parseInt(attrs, "rowHeight", _rowHeight));
				_headerHeight = Math.max(1, parseInt(attrs, "headerHeight", _headerHeight));
				_tabHeight = Math.max(1, parseInt(attrs, "tabHeight", _tabHeight));
				_iconSize = Math.max(1, parseInt(attrs, "iconSize", _iconSize));
				_maxPages = Math.max(1, parseInt(attrs, "maxPages", _maxPages));
				_pageHeight = Math.max(0, parseInt(attrs, "pageHeight", _pageHeight));
				_overhead = Math.max(0, parseInt(attrs, "overhead", _overhead));
				_nameChars = Math.max(0, parseInt(attrs, "nameChars", _nameChars));
				_ellipsis = parseString(attrs, "ellipsis", _ellipsis);

				_iconWidth = Math.max(1, parseInt(attrs, "iconWidth", _iconWidth));
				_nameWidth = Math.max(1, parseInt(attrs, "nameWidth", _nameWidth));
				_countWidth = Math.max(1, parseInt(attrs, "countWidth", _countWidth));
				_chanceWidth = Math.max(1, parseInt(attrs, "chanceWidth", _chanceWidth));

				final int total = _iconWidth + _nameWidth + _countWidth + _chanceWidth;
				if (total != _width)
					LOGGER.warn("The columns of the drop list layout sum up to {} instead of the layout width {} ; the rows won't be aligned.", total, _width);
			});

			forEach(listNode, "colors", colorsNode ->
			{
				final NamedNodeMap attrs = colorsNode.getAttributes();

				_highChance = Math.max(0, parseInt(attrs, "highChanceFrom", _highChance));
				_mediumChance = Math.max(0, parseInt(attrs, "mediumChanceFrom", _mediumChance));

				_rowColor = parseToken(attrs, "row", _rowColor);
				_altRowColor = parseToken(attrs, "altRow", _altRowColor);
				_headerColor = parseToken(attrs, "header", _headerColor);
				_headerTextColor = parseToken(attrs, "headerText", _headerTextColor);
				_titleColor = parseToken(attrs, "title", _titleColor);
				_tabBarColor = parseToken(attrs, "tabBar", _tabBarColor);
				_tabColor = parseToken(attrs, "tab", _tabColor);
				_activeTabColor = parseToken(attrs, "activeTab", _activeTabColor);
				_nameColor = parseToken(attrs, "name", _nameColor);
				_countColor = parseToken(attrs, "count", _countColor);
				_highChanceColor = parseToken(attrs, "highChance", _highChanceColor);
				_mediumChanceColor = parseToken(attrs, "mediumChance", _mediumChanceColor);
				_lowChanceColor = parseToken(attrs, "lowChance", _lowChanceColor);
				_disabledColor = parseToken(attrs, "disabled", _disabledColor);
				_pageColor = parseToken(attrs, "page", _pageColor);
				_activePageColor = parseToken(attrs, "activePage", _activePageColor);
			});

			forEach(listNode, "labels", labelsNode ->
			{
				final NamedNodeMap attrs = labelsNode.getAttributes();

				_itemHeader = parseString(attrs, "itemHeader", _itemHeader);
				_countHeader = parseString(attrs, "countHeader", _countHeader);
				_chanceHeader = parseString(attrs, "chanceHeader", _chanceHeader);
				_dropLabel = parseString(attrs, "drop", _dropLabel);
				_currencyLabel = parseString(attrs, "currency", _currencyLabel);
				_spoilLabel = parseString(attrs, "spoil", _spoilLabel);
				_herbLabel = parseString(attrs, "herb", _herbLabel);
				_emptyLabel = parseString(attrs, "empty", _emptyLabel);
				_prevPageLabel = parseString(attrs, "prevPage", _prevPageLabel);
				_nextPageLabel = parseString(attrs, "nextPage", _nextPageLabel);
			});
		});
	}

	/**
	 * Set the built-in layout, used as long as the XML doesn't override it. Every column width sums up to {@link #getWidth()}, which is mandatory to keep the rows aligned.
	 */
	private void setDefaultLayout()
	{
		_width = 280;
		_rowHeight = 36;
		_headerHeight = 18;
		_tabHeight = 18;
		_iconSize = 32;
		_maxPages = 10;
		_pageHeight = 440;
		_overhead = 96;
		_nameChars = 22;
		_ellipsis = "...";

		_iconWidth = 36;
		_nameWidth = 134;
		_countWidth = 56;
		_chanceWidth = 54;
	}

	/**
	 * Set the built-in colors, used as long as the XML doesn't override them. An empty {@link String} disables the related tag - a transparent background, or a raw text without any font.
	 */
	private void setDefaultColors()
	{
		_highChance = 80;
		_mediumChance = 5;

		_rowColor = "000000";
		_altRowColor = "";
		_headerColor = "000000";
		_headerTextColor = "9F9F9F";
		_titleColor = "LEVEL";
		_tabBarColor = "000000";
		_tabColor = "FFFFFF";
		_activeTabColor = "LEVEL";
		_nameColor = "";
		_countColor = "B09878";
		_highChanceColor = "90EE90";
		_mediumChanceColor = "BDB76B";
		_lowChanceColor = "F08080";
		_disabledColor = "707070";
		_pageColor = "";
		_activePageColor = "LEVEL";
	}

	private void setDefaultLabels()
	{
		_itemHeader = "Item";
		_countHeader = "Amount";
		_chanceHeader = "Chance";
		_dropLabel = "Drop";
		_currencyLabel = "Adena";
		_spoilLabel = "Spoil";
		_herbLabel = "Herbs";
		_emptyLabel = "-";
		_prevPageLabel = "<<";
		_nextPageLabel = ">>";
	}

	public void reload()
	{
		load();
	}

	/**
	 * A tolerant {@link IXmlReader#parseInteger(NamedNodeMap, String, Integer)}, since this file is meant to be hand tuned : a stray space around a value would otherwise throw, and take the whole
	 * server startup down with it.
	 * @param attrs : The attributes to read.
	 * @param name : The attribute name to read.
	 * @param defaultValue : The value returned when the attribute is missing, empty or not a number.
	 * @return The parsed value.
	 */
	private int parseInt(NamedNodeMap attrs, String name, int defaultValue)
	{
		final String value = parseTrimmed(attrs, name);
		if (value == null)
			return defaultValue;

		try
		{
			return Integer.parseInt(value);
		}
		catch (NumberFormatException e)
		{
			LOGGER.warn("The drop list attribute '{}' holds '{}', which isn't a number ; {} is used instead.", name, value, defaultValue);
			return defaultValue;
		}
	}

	/**
	 * Same as {@link IXmlReader#parseString(NamedNodeMap, String, String)}, minus the surrounding spaces - which would leak into a color and break the generated tag.
	 * @param attrs : The attributes to read.
	 * @param name : The attribute name to read.
	 * @param defaultValue : The value returned when the attribute is missing. An explicitly empty attribute stays empty.
	 * @return The trimmed value of the given attribute.
	 */
	private static String parseToken(NamedNodeMap attrs, String name, String defaultValue)
	{
		final Node node = attrs.getNamedItem(name);

		return (node == null) ? defaultValue : node.getNodeValue().trim();
	}

	/**
	 * @param attrs : The attributes to read.
	 * @param name : The attribute name to read.
	 * @return The trimmed value of the given attribute, null if it is missing or blank.
	 */
	private static String parseTrimmed(NamedNodeMap attrs, String name)
	{
		final Node node = attrs.getNamedItem(name);
		if (node == null)
			return null;

		final String value = node.getNodeValue().trim();

		return (value.isEmpty()) ? null : value;
	}

	/**
	 * @param type : The {@link DropType} to name.
	 * @return The label of the tab holding the given {@link DropType}.
	 */
	public String getTabLabel(DropType type)
	{
		switch (type)
		{
			case CURRENCY:
				return _currencyLabel;

			case SPOIL:
				return _spoilLabel;

			case HERB:
				return _herbLabel;

			default:
				return _dropLabel;
		}
	}

	/**
	 * @param chance : The already computed chance, in percent.
	 * @return The color the given chance is shown with.
	 */
	public String getChanceColor(double chance)
	{
		if (chance >= _highChance)
			return _highChanceColor;

		return (chance >= _mediumChance) ? _mediumChanceColor : _lowChanceColor;
	}

	public int getRowsPerPage()
	{
		return Config.DROPLIST_ROWS_PER_PAGE;
	}

	/**
	 * @return The width, in pixels, of every generated table - the tab bar, the header and the rows of the list.
	 */
	public int getWidth()
	{
		return _width;
	}

	/**
	 * @return The height, in pixels, of a single row of the list. It also drives the filler pushing the page selector to the bottom of the dialog.
	 */
	public int getRowHeight()
	{
		return _rowHeight;
	}

	public int getHeaderHeight()
	{
		return _headerHeight;
	}

	public int getTabHeight()
	{
		return _tabHeight;
	}

	/**
	 * @return The size, in pixels, the item icons are drawn at.
	 */
	public int getIconSize()
	{
		return _iconSize;
	}

	/**
	 * @return The maximum amount of page links shown by the page selector, centered on the current page.
	 */
	public int getMaxPages()
	{
		return _maxPages;
	}

	/**
	 * The dialog owns a fixed height ; padding every page up to that very same total keeps the page selector at one spot, and keeps the scrollbar shown on every single page.
	 * @return The height, in pixels, a page is padded up to - the tab bar, the HTM overhead and the list rows included. 0 disables the padding.
	 */
	public int getPageHeight()
	{
		return _pageHeight;
	}

	/**
	 * @return The height, in pixels, everything but the tab bar and the list rows takes on the HTM - separators, headline, header row and the footer row.
	 */
	public int getOverhead()
	{
		return _overhead;
	}

	/**
	 * @return The amount of characters above which an item name is shortened. 0 never shortens - and lets a long name wrap, which makes its row taller than the others.
	 */
	public int getNameChars()
	{
		return _nameChars;
	}

	/**
	 * @return The suffix appended to a shortened item name.
	 */
	public String getEllipsis()
	{
		return _ellipsis;
	}

	public int getIconWidth()
	{
		return _iconWidth;
	}

	public int getNameWidth()
	{
		return _nameWidth;
	}

	public int getCountWidth()
	{
		return _countWidth;
	}

	public int getChanceWidth()
	{
		return _chanceWidth;
	}

	/**
	 * @return The background color of the odd rows of the list.
	 */
	public String getRowColor()
	{
		return _rowColor;
	}

	/**
	 * @return The background color of the even rows of the list ; empty means transparent.
	 */
	public String getAltRowColor()
	{
		return _altRowColor;
	}

	public String getHeaderColor()
	{
		return _headerColor;
	}

	public String getHeaderTextColor()
	{
		return _headerTextColor;
	}

	/**
	 * @return The color of the headline of the dialog, fed to the HTM as %titleColor%.
	 */
	public String getTitleColor()
	{
		return _titleColor;
	}

	public String getTabBarColor()
	{
		return _tabBarColor;
	}

	public String getTabColor()
	{
		return _tabColor;
	}

	public String getActiveTabColor()
	{
		return _activeTabColor;
	}

	/**
	 * @return The color of the item names ; empty keeps the client default.
	 */
	public String getNameColor()
	{
		return _nameColor;
	}

	public String getCountColor()
	{
		return _countColor;
	}

	/**
	 * @return The color of the label shown instead of an empty list.
	 */
	public String getDisabledColor()
	{
		return _disabledColor;
	}

	public String getPageColor()
	{
		return _pageColor;
	}

	public String getActivePageColor()
	{
		return _activePageColor;
	}

	public String getItemHeader()
	{
		return _itemHeader;
	}

	public String getCountHeader()
	{
		return _countHeader;
	}

	public String getChanceHeader()
	{
		return _chanceHeader;
	}

	/**
	 * @return The label shown instead of an empty list.
	 */
	public String getEmptyLabel()
	{
		return _emptyLabel;
	}

	public String getPrevPageLabel()
	{
		return _prevPageLabel;
	}

	public String getNextPageLabel()
	{
		return _nextPageLabel;
	}

	public static DropListData getInstance()
	{
		return SingletonHolder.INSTANCE;
	}

	private static class SingletonHolder
	{
		protected static final DropListData INSTANCE = new DropListData();
	}
}
