package net.sf.l2j.gameserver.data.xml;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

import net.sf.l2j.commons.data.xml.IXmlReader;

import net.sf.l2j.Config;

import org.w3c.dom.Document;
import org.w3c.dom.NamedNodeMap;
import org.w3c.dom.Node;

/**
 * This class loads and stores the whole appearance of the raid boss book, described by data/xml/raidbook.xml.<br>
 * <br>
 * Everything the player sees is defined there : column widths and heights (&lt;layout&gt;), colors (&lt;colors&gt;), labels (&lt;labels&gt;) and the level ranges of the filter menu
 * (&lt;filters&gt;). The behavior is server side instead, on config/mods/raidbook.properties : whether the book exists at all, how many kills a hunting level takes, what a new level rewards, how many
 * points a kill is worth and how much damage a hunting level adds.<br>
 * <br>
 * The book itself is generated by {@link net.sf.l2j.gameserver.data.manager.RaidBookManager}.
 */
public class RaidBookData implements IXmlReader
{
	/** One entry of the level filter menu sitting on the head of the list. A range of 0 to 0 matches every raid boss, which is what the "all" entry is. */
	public record LevelFilter(String label, int min, int max)
	{
		public boolean matches(int level)
		{
			return (min <= 0 && max <= 0) || (level >= min && level <= max);
		}
	}

	private final List<LevelFilter> _filters = new ArrayList<>();

	private int _width;
	private int _rowHeight;
	private int _groupHeight;
	private int _headerHeight;
	private int _headerLabelWidth;
	private int _headerGap;
	private int _iconSize;
	private int _maxPages;
	private int _pageWidth;
	private int _pageHeight;
	private int _overhead;
	private int _nameChars;
	private int _bossNameChars;
	private String _ellipsis;
	private String _separator;

	private int _barWidth;
	private int _barHeight;
	private String _barFilled;
	private String _barEmpty;

	private int _listNameWidth;
	private int _listLevelWidth;
	private int _listButtonWidth;

	private int _dropIconWidth;
	private int _dropNameWidth;
	private int _dropChanceWidth;

	private int _rewardIconWidth;
	private int _rewardNameWidth;
	private int _rewardLevelWidth;

	private int _historyNameWidth;
	private int _historyClanWidth;
	private int _historyTimeWidth;

	private int _rankPosWidth;
	private int _rankNameWidth;
	private int _rankClanWidth;
	private int _rankPointsWidth;

	private int _screenTime;

	private int _highChance;
	private int _mediumChance;

	private String _rowColor;
	private String _altRowColor;
	private String _nameColor;
	private String _groupTextColor;
	private String _bossLevelColor;
	private String _huntLevelColor;
	private String _labelColor;
	private String _valueColor;
	private String _countColor;
	private String _tabColor;
	private String _activeTabColor;
	private String _filterColor;
	private String _activeFilterColor;
	private String _pageColor;
	private String _activePageColor;
	private String _selfColor;
	private String _disabledColor;
	private String _highChanceColor;
	private String _mediumChanceColor;
	private String _lowChanceColor;

	private String _bookTitle;
	private String _rankTitle;
	private String _dailyTitle;
	private String _dailyLabel;
	private String _placeSuffix;
	private String _dropGroupLabel;
	private String _numberPrefix;
	private String _colPosLabel;
	private String _colNameLabel;
	private String _colClanLabel;
	private String _colPointsLabel;
	private String _colKillsLabel;
	private String _colTimeLabel;
	private String _colRewardLabel;
	private String _colPlaceLabel;
	private String _killMessage;
	private String _levelUpMessage;
	private String _rewardMessage;
	private String _dailyMessage;
	private String _levelPrefix;
	private String _huntLevelPrefix;
	private String _detailsLabel;
	private String _searchLabel;
	private String _backLabel;
	private String _rankLabel;
	private String _rankPrefix;
	private String _unrankedLabel;
	private String _pointsLabel;
	private String _killsLabel;
	private String _huntLabel;
	private String _bonusLabel;
	private String _nextLevelLabel;
	private String _maxLevelLabel;
	private String _tabRewardsLabel;
	private String _tabDropLabel;
	private String _tabHistoryLabel;
	private String _tabRankLabel;
	private String _hpLabel;
	private String _mpLabel;
	private String _expLabel;
	private String _spLabel;
	private String _pAtkLabel;
	private String _pDefLabel;
	private String _atkSpdLabel;
	private String _mAtkLabel;
	private String _mDefLabel;
	private String _castSpdLabel;
	private String _noClanLabel;
	private String _emptyLabel;
	private String _notFoundLabel;
	private String _noLocationLabel;
	private String _searchDoneLabel;
	private String _countPrefix;
	private String _countRange;
	private String _chancePattern;
	private String _chanceSuffix;
	private String _nearZeroLabel;
	private String _timePattern;
	private String _prevPageLabel;
	private String _nextPageLabel;

	protected RaidBookData()
	{
		load();
	}

	@Override
	public void load()
	{
		setDefaultLayout();
		setDefaultColors();
		setDefaultLabels();

		_filters.clear();

		// IXmlReader only catches the parser exceptions ; without this, a single malformed attribute would abort the whole server startup.
		try
		{
			parseFile("./data/xml/raidbook.xml");
		}
		catch (Exception e)
		{
			LOGGER.error("Couldn't fully read raidbook.xml ; the raid boss book runs on whatever has been read so far.", e);
		}

		// Without a single filter the head of the list would hold an empty menu, and no raid boss would ever match.
		if (_filters.isEmpty())
			_filters.add(new LevelFilter("All", 0, 0));
	}

	@Override
	public void parseDocument(Document doc, Path path)
	{
		forEach(doc, "list", listNode ->
		{
			forEach(listNode, "layout", layoutNode ->
			{
				final NamedNodeMap attrs = layoutNode.getAttributes();

				_width = Math.max(1, parseInt(attrs, "width", _width));
				_rowHeight = Math.max(1, parseInt(attrs, "rowHeight", _rowHeight));
				_groupHeight = Math.max(1, parseInt(attrs, "groupHeight", _groupHeight));
				_headerHeight = Math.max(1, parseInt(attrs, "headerHeight", _headerHeight));
				_headerLabelWidth = Math.max(1, parseInt(attrs, "headerLabelWidth", _headerLabelWidth));
				_headerGap = Math.max(0, parseInt(attrs, "headerGap", _headerGap));
				_iconSize = Math.max(1, parseInt(attrs, "iconSize", _iconSize));
				_maxPages = Math.max(1, parseInt(attrs, "maxPages", _maxPages));
				_pageWidth = Math.max(1, parseInt(attrs, "pageWidth", _pageWidth));
				_pageHeight = Math.max(0, parseInt(attrs, "pageHeight", _pageHeight));
				_overhead = Math.max(0, parseInt(attrs, "overhead", _overhead));
				_nameChars = Math.max(0, parseInt(attrs, "nameChars", _nameChars));
				_bossNameChars = Math.max(0, parseInt(attrs, "bossNameChars", _bossNameChars));
				_ellipsis = parseString(attrs, "ellipsis", _ellipsis);
				_separator = parseToken(attrs, "separator", _separator);

				_barWidth = Math.max(1, parseInt(attrs, "barWidth", _barWidth));
				_barHeight = Math.max(1, parseInt(attrs, "barHeight", _barHeight));
				_barFilled = parseToken(attrs, "barFilled", _barFilled);
				_barEmpty = parseToken(attrs, "barEmpty", _barEmpty);

				_listNameWidth = Math.max(1, parseInt(attrs, "listNameWidth", _listNameWidth));
				_listLevelWidth = Math.max(1, parseInt(attrs, "listLevelWidth", _listLevelWidth));
				_listButtonWidth = Math.max(1, parseInt(attrs, "listButtonWidth", _listButtonWidth));

				_dropIconWidth = Math.max(1, parseInt(attrs, "dropIconWidth", _dropIconWidth));
				_dropNameWidth = Math.max(1, parseInt(attrs, "dropNameWidth", _dropNameWidth));
				_dropChanceWidth = Math.max(1, parseInt(attrs, "dropChanceWidth", _dropChanceWidth));

				_rewardIconWidth = Math.max(1, parseInt(attrs, "rewardIconWidth", _rewardIconWidth));
				_rewardNameWidth = Math.max(1, parseInt(attrs, "rewardNameWidth", _rewardNameWidth));
				_rewardLevelWidth = Math.max(1, parseInt(attrs, "rewardLevelWidth", _rewardLevelWidth));

				_historyNameWidth = Math.max(1, parseInt(attrs, "historyNameWidth", _historyNameWidth));
				_historyClanWidth = Math.max(1, parseInt(attrs, "historyClanWidth", _historyClanWidth));
				_historyTimeWidth = Math.max(1, parseInt(attrs, "historyTimeWidth", _historyTimeWidth));

				_rankPosWidth = Math.max(1, parseInt(attrs, "rankPosWidth", _rankPosWidth));
				_rankNameWidth = Math.max(1, parseInt(attrs, "rankNameWidth", _rankNameWidth));
				_rankClanWidth = Math.max(1, parseInt(attrs, "rankClanWidth", _rankClanWidth));
				_rankPointsWidth = Math.max(1, parseInt(attrs, "rankPointsWidth", _rankPointsWidth));

				_screenTime = Math.max(0, parseInt(attrs, "screenTime", _screenTime));

				checkColumns("list", _listNameWidth + _listLevelWidth + _listButtonWidth);
				checkColumns("drop", _dropIconWidth + _dropNameWidth + _dropChanceWidth);
				checkColumns("reward", _rewardIconWidth + _rewardNameWidth + _rewardLevelWidth);
				checkColumns("history", _historyNameWidth + _historyClanWidth + _historyTimeWidth);
				checkColumns("rank", _rankPosWidth + _rankNameWidth + _rankClanWidth + _rankPointsWidth);
			});

			forEach(listNode, "colors", colorsNode ->
			{
				final NamedNodeMap attrs = colorsNode.getAttributes();

				_highChance = Math.max(0, parseInt(attrs, "highChanceFrom", _highChance));
				_mediumChance = Math.max(0, parseInt(attrs, "mediumChanceFrom", _mediumChance));

				_rowColor = parseToken(attrs, "row", _rowColor);
				_altRowColor = parseToken(attrs, "altRow", _altRowColor);
				_nameColor = parseToken(attrs, "name", _nameColor);
				_groupTextColor = parseToken(attrs, "groupText", _groupTextColor);
				_bossLevelColor = parseToken(attrs, "bossLevel", _bossLevelColor);
				_huntLevelColor = parseToken(attrs, "huntLevel", _huntLevelColor);
				_labelColor = parseToken(attrs, "label", _labelColor);
				_valueColor = parseToken(attrs, "value", _valueColor);
				_countColor = parseToken(attrs, "count", _countColor);
				_tabColor = parseToken(attrs, "tab", _tabColor);
				_activeTabColor = parseToken(attrs, "activeTab", _activeTabColor);
				_filterColor = parseToken(attrs, "filter", _filterColor);
				_activeFilterColor = parseToken(attrs, "activeFilter", _activeFilterColor);
				_pageColor = parseToken(attrs, "page", _pageColor);
				_activePageColor = parseToken(attrs, "activePage", _activePageColor);
				_selfColor = parseToken(attrs, "self", _selfColor);
				_disabledColor = parseToken(attrs, "disabled", _disabledColor);
				_highChanceColor = parseToken(attrs, "highChance", _highChanceColor);
				_mediumChanceColor = parseToken(attrs, "mediumChance", _mediumChanceColor);
				_lowChanceColor = parseToken(attrs, "lowChance", _lowChanceColor);
			});

			forEach(listNode, "labels", labelsNode ->
			{
				final NamedNodeMap attrs = labelsNode.getAttributes();

				_bookTitle = parseString(attrs, "bookTitle", _bookTitle);
				_rankTitle = parseString(attrs, "rankTitle", _rankTitle);
				_dailyTitle = parseString(attrs, "dailyTitle", _dailyTitle);
				_dailyLabel = parseString(attrs, "daily", _dailyLabel);
				_placeSuffix = parseString(attrs, "placeSuffix", _placeSuffix);
				_dropGroupLabel = parseString(attrs, "dropGroup", _dropGroupLabel);
				_numberPrefix = parseString(attrs, "numberPrefix", _numberPrefix);
				_colPosLabel = parseString(attrs, "colPos", _colPosLabel);
				_colNameLabel = parseString(attrs, "colName", _colNameLabel);
				_colClanLabel = parseString(attrs, "colClan", _colClanLabel);
				_colPointsLabel = parseString(attrs, "colPoints", _colPointsLabel);
				_colKillsLabel = parseString(attrs, "colKills", _colKillsLabel);
				_colTimeLabel = parseString(attrs, "colTime", _colTimeLabel);
				_colRewardLabel = parseString(attrs, "colReward", _colRewardLabel);
				_colPlaceLabel = parseString(attrs, "colPlace", _colPlaceLabel);
				_killMessage = parseString(attrs, "msgKill", _killMessage);
				_levelUpMessage = parseString(attrs, "msgLevelUp", _levelUpMessage);
				_rewardMessage = parseString(attrs, "msgReward", _rewardMessage);
				_dailyMessage = parseString(attrs, "msgDaily", _dailyMessage);
				_levelPrefix = parseString(attrs, "levelPrefix", _levelPrefix);
				_huntLevelPrefix = parseString(attrs, "huntLevelPrefix", _huntLevelPrefix);
				_detailsLabel = parseString(attrs, "details", _detailsLabel);
				_searchLabel = parseString(attrs, "search", _searchLabel);
				_backLabel = parseString(attrs, "back", _backLabel);
				_rankLabel = parseString(attrs, "rank", _rankLabel);
				_rankPrefix = parseString(attrs, "rankPrefix", _rankPrefix);
				_unrankedLabel = parseString(attrs, "unranked", _unrankedLabel);
				_pointsLabel = parseString(attrs, "points", _pointsLabel);
				_killsLabel = parseString(attrs, "kills", _killsLabel);
				_huntLabel = parseString(attrs, "hunt", _huntLabel);
				_bonusLabel = parseString(attrs, "bonus", _bonusLabel);
				_nextLevelLabel = parseString(attrs, "nextLevel", _nextLevelLabel);
				_maxLevelLabel = parseString(attrs, "maxLevel", _maxLevelLabel);
				_tabRewardsLabel = parseString(attrs, "tabRewards", _tabRewardsLabel);
				_tabDropLabel = parseString(attrs, "tabDrop", _tabDropLabel);
				_tabHistoryLabel = parseString(attrs, "tabHistory", _tabHistoryLabel);
				_tabRankLabel = parseString(attrs, "tabRank", _tabRankLabel);
				_hpLabel = parseString(attrs, "hp", _hpLabel);
				_mpLabel = parseString(attrs, "mp", _mpLabel);
				_expLabel = parseString(attrs, "exp", _expLabel);
				_spLabel = parseString(attrs, "sp", _spLabel);
				_pAtkLabel = parseString(attrs, "pAtk", _pAtkLabel);
				_pDefLabel = parseString(attrs, "pDef", _pDefLabel);
				_atkSpdLabel = parseString(attrs, "atkSpd", _atkSpdLabel);
				_mAtkLabel = parseString(attrs, "mAtk", _mAtkLabel);
				_mDefLabel = parseString(attrs, "mDef", _mDefLabel);
				_castSpdLabel = parseString(attrs, "castSpd", _castSpdLabel);
				_noClanLabel = parseString(attrs, "noClan", _noClanLabel);
				_emptyLabel = parseString(attrs, "empty", _emptyLabel);
				_notFoundLabel = parseString(attrs, "notFound", _notFoundLabel);
				_noLocationLabel = parseString(attrs, "noLocation", _noLocationLabel);
				_searchDoneLabel = parseString(attrs, "searchDone", _searchDoneLabel);
				_countPrefix = parseString(attrs, "countPrefix", _countPrefix);
				_countRange = parseString(attrs, "countRange", _countRange);
				_chancePattern = parseToken(attrs, "chancePattern", _chancePattern);
				_chanceSuffix = parseString(attrs, "chanceSuffix", _chanceSuffix);
				_nearZeroLabel = parseString(attrs, "nearZero", _nearZeroLabel);
				_timePattern = parseToken(attrs, "timePattern", _timePattern);
				_prevPageLabel = parseString(attrs, "prevPage", _prevPageLabel);
				_nextPageLabel = parseString(attrs, "nextPage", _nextPageLabel);
			});

			forEach(listNode, "filters", filtersNode -> forEach(filtersNode, "filter", filterNode ->
			{
				final NamedNodeMap attrs = filterNode.getAttributes();

				_filters.add(new LevelFilter(parseString(attrs, "label", "?"), Math.max(0, parseInt(attrs, "min", 0)), Math.max(0, parseInt(attrs, "max", 0))));
			}));
		});
	}

	/**
	 * The rows of a table are generated out of fixed column widths ; a set which doesn't sum up to the layout width simply doesn't align.
	 * @param name : The name of the checked table, used by the warning.
	 * @param total : The sum of the column widths of that table.
	 */
	private void checkColumns(String name, int total)
	{
		if (total != _width)
			LOGGER.warn("The {} columns of the raid boss book sum up to {} instead of the layout width {} ; the rows won't be aligned.", name, total, _width);
	}

	private void setDefaultLayout()
	{
		_width = 280;
		_rowHeight = 36;
		_groupHeight = 18;
		_headerHeight = 16;
		_headerLabelWidth = 76;
		_headerGap = 6;
		_iconSize = 32;
		_maxPages = 10;
		_pageWidth = 26;
		_pageHeight = 440;
		_overhead = 27;
		_nameChars = 24;
		_bossNameChars = 17;
		_ellipsis = "...";
		_separator = "L2UI.SquareGray";

		_barWidth = 96;
		_barHeight = 7;
		_barFilled = "L2UI.SquareWhite";
		_barEmpty = "L2UI.SquareGray";

		_listNameWidth = 160;
		_listLevelWidth = 54;
		_listButtonWidth = 66;

		_dropIconWidth = 36;
		_dropNameWidth = 190;
		_dropChanceWidth = 54;

		_rewardIconWidth = 36;
		_rewardNameWidth = 190;
		_rewardLevelWidth = 54;

		_historyNameWidth = 108;
		_historyClanWidth = 92;
		_historyTimeWidth = 80;

		_rankPosWidth = 30;
		_rankNameWidth = 104;
		_rankClanWidth = 78;
		_rankPointsWidth = 68;

		_screenTime = 5000;
	}

	private void setDefaultColors()
	{
		_highChance = 80;
		_mediumChance = 5;

		_rowColor = "000000";
		_altRowColor = "";
		_nameColor = "";
		_groupTextColor = "LEVEL";
		_bossLevelColor = "B09878";
		_huntLevelColor = "LEVEL";
		_labelColor = "B09878";
		_valueColor = "FFFFFF";
		_countColor = "B09878";
		_tabColor = "";
		_activeTabColor = "LEVEL";
		_filterColor = "";
		_activeFilterColor = "LEVEL";
		_pageColor = "";
		_activePageColor = "LEVEL";
		_selfColor = "LEVEL";
		_disabledColor = "707070";
		_highChanceColor = "90EE90";
		_mediumChanceColor = "BDB76B";
		_lowChanceColor = "F08080";
	}

	private void setDefaultLabels()
	{
		_bookTitle = "Raid Boss Book";
		_rankTitle = "Ranking";
		_dailyTitle = "Daily rewards";
		_dailyLabel = "Daily rewards";
		_placeSuffix = " place";
		_dropGroupLabel = "Drop";
		_numberPrefix = " #";
		_colPosLabel = "#";
		_colNameLabel = "Name";
		_colClanLabel = "Clan";
		_colPointsLabel = "Points";
		_colKillsLabel = "Kills";
		_colTimeLabel = "Date";
		_colRewardLabel = "Reward";
		_colPlaceLabel = "Place";
		_killMessage = "%boss% : +%points% ranking points.";
		_levelUpMessage = "Hunting level %level% reached on %boss% !";
		_rewardMessage = "Hunting level %level% reward : %item% x%count%.";
		_dailyMessage = "Daily reward for the %place% place : %item% x%count%.";
		_levelPrefix = "Lv.";
		_huntLevelPrefix = "Hunt ";
		_detailsLabel = "Info";
		_searchLabel = "Search";
		_backLabel = "Back";
		_rankLabel = "Ranking";
		_rankPrefix = "Rank ";
		_unrankedLabel = "-";
		_pointsLabel = " pts";
		_killsLabel = "Kills";
		_huntLabel = "Hunt level";
		_bonusLabel = "Damage bonus";
		_nextLevelLabel = "Next level";
		_maxLevelLabel = "-";
		_tabRewardsLabel = "Rewards";
		_tabDropLabel = "Drop";
		_tabHistoryLabel = "History";
		_tabRankLabel = "Ranking";
		_hpLabel = "HP";
		_mpLabel = "MP";
		_expLabel = "Exp";
		_spLabel = "SP";
		_pAtkLabel = "P. Atk.";
		_pDefLabel = "P. Def.";
		_atkSpdLabel = "Atk. Spd.";
		_mAtkLabel = "M. Atk.";
		_mDefLabel = "M. Def.";
		_castSpdLabel = "Casting Spd.";
		_noClanLabel = "-";
		_emptyLabel = "-";
		_notFoundLabel = "Unknown raid boss.";
		_noLocationLabel = "Unknown location.";
		_searchDoneLabel = "The location has been marked on your map.";
		_countPrefix = "x";
		_countRange = "-";
		_chancePattern = "#0.##";
		_chanceSuffix = "%";
		_nearZeroLabel = "&lt;0.01%";
		_timePattern = "dd.MM HH:mm";
		_prevPageLabel = "<<";
		_nextPageLabel = ">>";
	}

	public void reload()
	{
		load();
	}

	/**
	 * A tolerant {@link IXmlReader#parseInteger(NamedNodeMap, String, Integer)}, since this file is meant to be hand tuned : a stray space around a value would otherwise throw, and take the whole
	 * server startup down with it.
	 * @param attrs : The attributes to read.
	 * @param name : The attribute name to read.
	 * @param defaultValue : The value returned when the attribute is missing, empty or not a number.
	 * @return The parsed value.
	 */
	private int parseInt(NamedNodeMap attrs, String name, int defaultValue)
	{
		final Node node = attrs.getNamedItem(name);
		if (node == null)
			return defaultValue;

		final String value = node.getNodeValue().trim();
		if (value.isEmpty())
			return defaultValue;

		try
		{
			return Integer.parseInt(value);
		}
		catch (NumberFormatException e)
		{
			LOGGER.warn("The raid boss book attribute '{}' holds '{}', which isn't a number ; {} is used instead.", name, value, defaultValue);
			return defaultValue;
		}
	}

	/**
	 * Same as {@link IXmlReader#parseString(NamedNodeMap, String, String)}, minus the surrounding spaces - which would leak into a color and break the generated tag.
	 * @param attrs : The attributes to read.
	 * @param name : The attribute name to read.
	 * @param defaultValue : The value returned when the attribute is missing. An explicitly empty attribute stays empty.
	 * @return The trimmed value of the given attribute.
	 */
	private static String parseToken(NamedNodeMap attrs, String name, String defaultValue)
	{
		final Node node = attrs.getNamedItem(name);

		return (node == null) ? defaultValue : node.getNodeValue().trim();
	}

	/**
	 * @return The level ranges of the filter menu sitting on the head of the list, in the very order they are shown.
	 */
	public List<LevelFilter> getFilters()
	{
		return _filters;
	}

	/**
	 * @param index : The index of the wanted filter.
	 * @return The {@link LevelFilter} of the given index, the first one when the index is out of the list.
	 */
	public LevelFilter getFilter(int index)
	{
		return _filters.get((index < 0 || index >= _filters.size()) ? 0 : index);
	}

	/**
	 * @param chance : The already computed chance, in percent.
	 * @return The color the given chance is shown with.
	 */
	public String getChanceColor(double chance)
	{
		if (chance >= _highChance)
			return _highChanceColor;

		return (chance >= _mediumChance) ? _mediumChanceColor : _lowChanceColor;
	}

	public int getRowsPerPage()
	{
		return Config.RAIDBOOK_ROWS_PER_PAGE;
	}

	public int getWidth()
	{
		return _width;
	}

	/**
	 * A row of the main list is two stacked tables - the name line and the progress bar line - so this is the height of both of them together : the bar line takes whatever
	 * {@link #getGroupHeight()} leaves of it.
	 * @return The total height, in pixels, of a row of the main list.
	 */
	public int getRowHeight()
	{
		return _rowHeight;
	}

	/**
	 * @return The height, in pixels, of the one line rows - the tab menu, the filter menu, the page selector and the rows of the drop, history and ranking tabs.
	 */
	public int getGroupHeight()
	{
		return _groupHeight;
	}

	public int getHeaderHeight()
	{
		return _headerHeight;
	}

	public int getHeaderLabelWidth()
	{
		return _headerLabelWidth;
	}

	public int getHeaderGap()
	{
		return _headerGap;
	}

	public int getIconSize()
	{
		return _iconSize;
	}

	public int getMaxPages()
	{
		return _maxPages;
	}

	public int getPageWidth()
	{
		return _pageWidth;
	}

	public int getPageHeight()
	{
		return _pageHeight;
	}

	public int getOverhead()
	{
		return _overhead;
	}

	public int getNameChars()
	{
		return _nameChars;
	}

	/**
	 * The name of a raid boss shares its line with the level of that boss, and a wrapped line makes its whole row taller than the ones around it - so it gets a limit of its own, tighter than the one
	 * of the item and character names, which own their column whole.
	 * @return The amount of characters above which the name of a raid boss is shortened. 0 never shortens.
	 */
	public int getBossNameChars()
	{
		return _bossNameChars;
	}

	public String getEllipsis()
	{
		return _ellipsis;
	}

	public String getSeparator()
	{
		return _separator;
	}

	/**
	 * @return The width, in pixels, of the whole progress bar - the filled part and the empty one summed up.
	 */
	public int getBarWidth()
	{
		return _barWidth;
	}

	public int getBarHeight()
	{
		return _barHeight;
	}

	/**
	 * @return The client texture the filled part of a progress bar is drawn with.
	 */
	public String getBarFilled()
	{
		return _barFilled;
	}

	/**
	 * @return The client texture the empty part of a progress bar is drawn with.
	 */
	public String getBarEmpty()
	{
		return _barEmpty;
	}

	public int getListNameWidth()
	{
		return _listNameWidth;
	}

	public int getListLevelWidth()
	{
		return _listLevelWidth;
	}

	public int getListButtonWidth()
	{
		return _listButtonWidth;
	}

	public int getDropIconWidth()
	{
		return _dropIconWidth;
	}

	public int getDropNameWidth()
	{
		return _dropNameWidth;
	}

	public int getDropChanceWidth()
	{
		return _dropChanceWidth;
	}

	public int getRewardIconWidth()
	{
		return _rewardIconWidth;
	}

	public int getRewardNameWidth()
	{
		return _rewardNameWidth;
	}

	public int getRewardLevelWidth()
	{
		return _rewardLevelWidth;
	}

	public int getHistoryNameWidth()
	{
		return _historyNameWidth;
	}

	public int getHistoryClanWidth()
	{
		return _historyClanWidth;
	}

	public int getHistoryTimeWidth()
	{
		return _historyTimeWidth;
	}

	public int getRankPosWidth()
	{
		return _rankPosWidth;
	}

	public int getRankNameWidth()
	{
		return _rankNameWidth;
	}

	public int getRankClanWidth()
	{
		return _rankClanWidth;
	}

	public int getRankPointsWidth()
	{
		return _rankPointsWidth;
	}

	/**
	 * @return The time, in milliseconds, an informational message stays on the screen of the {@link net.sf.l2j.gameserver.model.actor.Player} it is sent to.
	 */
	public int getScreenTime()
	{
		return _screenTime;
	}

	/**
	 * @return The color of the caption of a drop group header.
	 */
	public String getGroupTextColor()
	{
		return _groupTextColor;
	}

	public String getDailyTitle()
	{
		return _dailyTitle;
	}

	/**
	 * @return The caption of the link leading from the ladder to the daily reward page.
	 */
	public String getDailyLabel()
	{
		return _dailyLabel;
	}

	/**
	 * @return The text appended to a ranking position on the daily reward page, "1" reading as "1 place".
	 */
	public String getPlaceSuffix()
	{
		return _placeSuffix;
	}

	/**
	 * @param number : The rank of the group among the ones sharing its caption, 1 being the first.
	 * @return The caption of the header row of a drop group, being "Drop #1" out of the box.
	 */
	public String getDropGroupLabel(int number)
	{
		return _dropGroupLabel + _numberPrefix + number;
	}

	/**
	 * @return The caption of the ranking position column.
	 */
	public String getColPosLabel()
	{
		return _colPosLabel;
	}

	/**
	 * @return The caption of the character name column.
	 */
	public String getColNameLabel()
	{
		return _colNameLabel;
	}

	/**
	 * @return The caption of the clan column.
	 */
	public String getColClanLabel()
	{
		return _colClanLabel;
	}

	/**
	 * @return The caption of the score column of the server wide ladder.
	 */
	public String getColPointsLabel()
	{
		return _colPointsLabel;
	}

	/**
	 * @return The caption of the score column of a per boss ladder, which counts kills rather than points.
	 */
	public String getColKillsLabel()
	{
		return _colKillsLabel;
	}

	/**
	 * @return The caption of the kill date column of the history.
	 */
	public String getColTimeLabel()
	{
		return _colTimeLabel;
	}

	/**
	 * @return The caption of the item column of the daily reward page.
	 */
	public String getColRewardLabel()
	{
		return _colRewardLabel;
	}

	/**
	 * @return The caption of the ranking position column of the daily reward page.
	 */
	public String getColPlaceLabel()
	{
		return _colPlaceLabel;
	}

	/**
	 * @return The message sent on a raid boss kill, holding the %boss% and %points% variables.
	 */
	public String getKillMessage()
	{
		return _killMessage;
	}

	/**
	 * @return The message sent when a hunting level is reached, holding the %boss% and %level% variables.
	 */
	public String getLevelUpMessage()
	{
		return _levelUpMessage;
	}

	/**
	 * @return The message sent along a hunting level reward, holding the %level%, %item% and %count% variables.
	 */
	public String getRewardMessage()
	{
		return _rewardMessage;
	}

	/**
	 * @return The message sent along a daily ranking reward, holding the %place%, %item% and %count% variables.
	 */
	public String getDailyMessage()
	{
		return _dailyMessage;
	}

	public String getRowColor()
	{
		return _rowColor;
	}

	public String getAltRowColor()
	{
		return _altRowColor;
	}

	public String getNameColor()
	{
		return _nameColor;
	}

	public String getBossLevelColor()
	{
		return _bossLevelColor;
	}

	public String getHuntLevelColor()
	{
		return _huntLevelColor;
	}

	public String getLabelColor()
	{
		return _labelColor;
	}

	public String getValueColor()
	{
		return _valueColor;
	}

	public String getCountColor()
	{
		return _countColor;
	}

	public String getTabColor()
	{
		return _tabColor;
	}

	public String getActiveTabColor()
	{
		return _activeTabColor;
	}

	public String getFilterColor()
	{
		return _filterColor;
	}

	public String getActiveFilterColor()
	{
		return _activeFilterColor;
	}

	public String getPageColor()
	{
		return _pageColor;
	}

	public String getActivePageColor()
	{
		return _activePageColor;
	}

	/**
	 * @return The color the row of the very {@link net.sf.l2j.gameserver.model.actor.Player} browsing the ranking is written with.
	 */
	public String getSelfColor()
	{
		return _selfColor;
	}

	public String getDisabledColor()
	{
		return _disabledColor;
	}

	public String getBookTitle()
	{
		return _bookTitle;
	}

	public String getRankTitle()
	{
		return _rankTitle;
	}

	/**
	 * @return The text put in front of the level of a raid boss.
	 */
	public String getLevelPrefix()
	{
		return _levelPrefix;
	}

	/**
	 * @return The text put in front of the hunting level of a {@link net.sf.l2j.gameserver.model.actor.Player} on a raid boss.
	 */
	public String getHuntLevelPrefix()
	{
		return _huntLevelPrefix;
	}

	public String getDetailsLabel()
	{
		return _detailsLabel;
	}

	public String getSearchLabel()
	{
		return _searchLabel;
	}

	public String getBackLabel()
	{
		return _backLabel;
	}

	public String getRankLabel()
	{
		return _rankLabel;
	}

	public String getRankPrefix()
	{
		return _rankPrefix;
	}

	/**
	 * @return The label shown instead of a ranking position, to whoever holds no point at all.
	 */
	public String getUnrankedLabel()
	{
		return _unrankedLabel;
	}

	/**
	 * @return The text appended to the amount of ranking points shown on the head of a page - a bare number wouldn't tell what it counts.
	 */
	public String getPointsLabel()
	{
		return _pointsLabel;
	}

	public String getKillsLabel()
	{
		return _killsLabel;
	}

	public String getHuntLabel()
	{
		return _huntLabel;
	}

	public String getBonusLabel()
	{
		return _bonusLabel;
	}

	public String getNextLevelLabel()
	{
		return _nextLevelLabel;
	}

	/**
	 * @return The label shown instead of the amount of kills left, when the hunting levels are capped and the cap has been reached.
	 */
	public String getMaxLevelLabel()
	{
		return _maxLevelLabel;
	}

	public String getTabRewardsLabel()
	{
		return _tabRewardsLabel;
	}

	public String getTabDropLabel()
	{
		return _tabDropLabel;
	}

	public String getTabHistoryLabel()
	{
		return _tabHistoryLabel;
	}

	public String getTabRankLabel()
	{
		return _tabRankLabel;
	}

	public String getHpLabel()
	{
		return _hpLabel;
	}

	public String getMpLabel()
	{
		return _mpLabel;
	}

	public String getExpLabel()
	{
		return _expLabel;
	}

	public String getSpLabel()
	{
		return _spLabel;
	}

	public String getPAtkLabel()
	{
		return _pAtkLabel;
	}

	public String getPDefLabel()
	{
		return _pDefLabel;
	}

	public String getAtkSpdLabel()
	{
		return _atkSpdLabel;
	}

	public String getMAtkLabel()
	{
		return _mAtkLabel;
	}

	public String getMDefLabel()
	{
		return _mDefLabel;
	}

	public String getCastSpdLabel()
	{
		return _castSpdLabel;
	}

	/**
	 * @return The label shown instead of the clan of a killer who had none.
	 */
	public String getNoClanLabel()
	{
		return _noClanLabel;
	}

	public String getEmptyLabel()
	{
		return _emptyLabel;
	}

	public String getNotFoundLabel()
	{
		return _notFoundLabel;
	}

	/**
	 * @return The message sent to whoever asks for a raid boss which owns no spawn point at all.
	 */
	public String getNoLocationLabel()
	{
		return _noLocationLabel;
	}

	/**
	 * @return The message sent along the radar marker.
	 */
	public String getSearchDoneLabel()
	{
		return _searchDoneLabel;
	}

	public String getCountPrefix()
	{
		return _countPrefix;
	}

	public String getCountRange()
	{
		return _countRange;
	}

	public String getChancePattern()
	{
		return _chancePattern;
	}

	public String getChanceSuffix()
	{
		return _chanceSuffix;
	}

	public String getNearZeroLabel()
	{
		return _nearZeroLabel;
	}

	/**
	 * @return The {@link java.text.SimpleDateFormat} pattern a kill date of the history is rendered with.
	 */
	public String getTimePattern()
	{
		return _timePattern;
	}

	public String getPrevPageLabel()
	{
		return _prevPageLabel;
	}

	public String getNextPageLabel()
	{
		return _nextPageLabel;
	}

	public static RaidBookData getInstance()
	{
		return SingletonHolder.INSTANCE;
	}

	private static class SingletonHolder
	{
		protected static final RaidBookData INSTANCE = new RaidBookData();
	}
}
