package net.sf.l2j.gameserver.handler.itemhandlers;

import net.sf.l2j.gameserver.data.manager.RaidBookManager;
import net.sf.l2j.gameserver.handler.IItemHandler;
import net.sf.l2j.gameserver.model.actor.Playable;
import net.sf.l2j.gameserver.model.actor.Player;
import net.sf.l2j.gameserver.model.item.instance.ItemInstance;

/**
 * Opens the raid boss book, generated by {@link RaidBookManager}.<br>
 * <br>
 * The handler is bound to the item by the "handler" attribute of data/xml/items, so which item carries the book - and how a player gets it - is a datapack matter, not a server side one.
 */
public class RaidBossBook implements IItemHandler
{
	@Override
	public void useItem(Playable playable, ItemInstance item, boolean forceUse)
	{
		if (!(playable instanceof Player player))
			return;

		RaidBookManager.getInstance().show(player);
	}
}
