package net.sf.l2j.gameserver.model.actor.instance;

import net.sf.l2j.Config;
import net.sf.l2j.gameserver.data.manager.RaidBookManager;
import net.sf.l2j.gameserver.model.actor.Player;
import net.sf.l2j.gameserver.model.actor.template.NpcTemplate;

/**
 * The Adventure Guildsman, which is the one and only way into the raid boss book generated by {@link RaidBookManager}.<br>
 * <br>
 * Talking to it opens that book straight away : holding the book is the whole point of that npc now, so a dialog offering it as one entry among others would be a click asking nothing. A server which
 * switched the book off falls back on the stock chat window, so the npc still answers rather than swallowing the click.
 */
public class Adventurer extends Folk
{
	public Adventurer(int objectId, NpcTemplate template)
	{
		super(objectId, template);
	}

	@Override
	public void showChatWindow(Player player, int val)
	{
		if (!Config.RAIDBOOK_ENABLED)
		{
			super.showChatWindow(player, val);
			return;
		}

		RaidBookManager.getInstance().show(player);
	}
}
