package net.sf.l2j.gameserver.model.gatekeeper;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import net.sf.l2j.gameserver.enums.GatekeeperTabType;

/**
 * A single entry of the {@link GatekeeperMenu} top bar.
 */
public class GatekeeperTab
{
	private final List<GatekeeperArea> _areas = new ArrayList<>();

	private final int _index;
	private final String _name;
	private final String _color;
	private final GatekeeperTabType _type;
	private final String _bypass;
	private final String _page;

	public GatekeeperTab(int index, String name, String color, GatekeeperTabType type, String bypass, String page)
	{
		_index = index;
		_name = name;
		_color = color;
		_type = type;
		_bypass = bypass;
		_page = page;
	}

	@Override
	public String toString()
	{
		return "GatekeeperTab [_index=" + _index + ", _name=" + _name + ", _type=" + _type + ", _areas=" + _areas.size() + "]";
	}

	public int getIndex()
	{
		return _index;
	}

	public String getName()
	{
		return _name;
	}

	public String getColor()
	{
		return _color;
	}

	public GatekeeperTabType getType()
	{
		return _type;
	}

	/**
	 * @return The bypass fired by this tab. Internal types own a generated bypass, while {@link GatekeeperTabType#EXTERNAL} uses the XML defined one.
	 */
	public String getBypass()
	{
		return _bypass;
	}

	/**
	 * @return The datapack HTM filename, only set for {@link GatekeeperTabType#PAGE}.
	 */
	public String getPage()
	{
		return _page;
	}

	public List<GatekeeperArea> getAreas()
	{
		return Collections.unmodifiableList(_areas);
	}

	public void addArea(GatekeeperArea area)
	{
		_areas.add(area);
	}

	public GatekeeperArea getArea(int index)
	{
		return (index < 0 || index >= _areas.size()) ? null : _areas.get(index);
	}
}
