package net.sf.l2j.gameserver.model.gatekeeper;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import net.sf.l2j.gameserver.enums.GatekeeperTabType;

/**
 * A single entry of the {@link GatekeeperMenu} top bar.
 */
public class GatekeeperTab
{
	private final List<GatekeeperArea> _areas = new ArrayList<>();

	private final int _index;
	private final String _name;
	private final String _color;
	private final GatekeeperTabType _type;
	private final String _tableId;
	private final String _bypass;
	private final String _page;
	private final String _intro;
	private final int _introHeight;

	public GatekeeperTab(int index, String name, String color, GatekeeperTabType type, String tableId, String bypass, String page, String intro, int introHeight)
	{
		_index = index;
		_name = name;
		_color = color;
		_type = type;
		_tableId = tableId;
		_bypass = bypass;
		_page = page;
		_intro = intro;
		_introHeight = introHeight;
	}

	@Override
	public String toString()
	{
		return "GatekeeperTab [_index=" + _index + ", _name=" + _name + ", _type=" + _type + ", _areas=" + _areas.size() + "]";
	}

	public int getIndex()
	{
		return _index;
	}

	public String getName()
	{
		return _name;
	}

	public String getColor()
	{
		return _color;
	}

	public GatekeeperTabType getType()
	{
		return _type;
	}

	/**
	 * A tab can pick any &lt;table&gt; of the layout through its "table" attribute, which is how two tabs of the very same {@link GatekeeperTabType} can own different columns - a tab mixing areas and
	 * direct points wants a level column where a plain areas tab wants a capital one.
	 * @return The id of the {@link GatekeeperTable} used to render the list of this tab, defaulting to the one of its {@link GatekeeperTabType}.
	 */
	public String getTableId()
	{
		return _tableId;
	}

	/**
	 * @return The bypass fired by this tab. Internal types own a generated bypass, while {@link GatekeeperTabType#EXTERNAL} uses the XML defined one.
	 */
	public String getBypass()
	{
		return _bypass;
	}

	/**
	 * @return The datapack HTM filename, only set for {@link GatekeeperTabType#PAGE}.
	 */
	public String getPage()
	{
		return _page;
	}

	/**
	 * @return The datapack HTM fragment shown above the tab bar of the areas list page, replacing its %intro% variable - null when this tab doesn't own one.
	 */
	public String getIntro()
	{
		return _intro;
	}

	/**
	 * @return The height, in pixels, of the intro fragment. Added to the overhead of the page, since the script can't measure a text on its own.
	 */
	public int getIntroHeight()
	{
		return _introHeight;
	}

	public List<GatekeeperArea> getAreas()
	{
		return Collections.unmodifiableList(_areas);
	}

	public void addArea(GatekeeperArea area)
	{
		_areas.add(area);
	}

	public GatekeeperArea getArea(int index)
	{
		return (index < 0 || index >= _areas.size()) ? null : _areas.get(index);
	}

	/**
	 * @return True if this tab directly shows teleport points, without any intermediate areas list.
	 */
	public boolean isFlat()
	{
		return _type == GatekeeperTabType.POINTS;
	}
}
