CREATE TABLE IF NOT EXISTS `character_offline_trade` (
  `charId` INT UNSIGNED NOT NULL DEFAULT '0',
  `time` BIGINT UNSIGNED NOT NULL DEFAULT '0',
  `type` TINYINT UNSIGNED NOT NULL DEFAULT '0',
  `title` VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (`charId`)
);
